version: '3.8'
services:
  backend:
    build: ./server
    container_name: altay_chat_backend
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./server:/app
  frontend:
    build: ./front
    container_name: altay_chat_frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./front:/app
    stdin_open: true
    tty: true